// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  xlgenSidebar: [{ type: 'autogenerated', dirName: '.' }],
  librarySidebar: [{ type: 'autogenerated', dirName: '.' }],
  papersSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;